import moment from "moment";
import * as Yup from "yup";
export const LicenseValidationSchema = Yup.object({});

export const LicenseInitialValues = {
  qr_code: "",
  id: "",
  license_number_secretariat: "",
  license_number: "",
  request_number: "",
  license_start_date: "",
  license_end_date: "",
  license_type: "",
  building_type: "",
  buildings_number: "",
  license_separated_another_license: "",
  main_use: "",
  sub_use: "",
  total_land_area: "",
  building_description: "",
  applicant_characteristics: "",
  applicant_id: "",
  applicant_name: "",
  phone: "",
  email: "",
  ownership_type: "",
  ownership_number: "",
  ownership_date: "",
  scheme_number: "",
  plot_number: "",
  survey_decision_number: "",
  survey_decision_date: "",
  honesty: "",
  municipal: "",
  district: "",
  planned_number: "",
  block_number: "",
  abscissa: "",
  y_coordinate: "",
  supervising_engineering_office: "",
  designer_engineering_office: "",
  ownerData: [],
  landData: [],
  buildingComponents: [],
  coordinates: [],
  pledges: [],
  north_instrument_limit: "",
  east_instrument_limit: "",
  south_instrument_limit: "",
  west_instrument_limit: "",
  north_nature_limit: "",
  east_nature_limit: "",
  south_nature_limit: "",
  west_nature_limit: "",
  north_instrument_length: "",
  east_instrument_length: "",
  south_instrument_length: "",
  west_instrument_length: "",
  north_nature_length: "",
  east_nature_length: "",
  south_nature_length: "",
  west_nature_length: "",
  north_bouncing: "",
  east_bouncing: "",
  south_bouncing: "",
  west_bouncing: "",
  north_prominence: "",
  east_prominence: "",
  south_prominence: "",
  west_prominence: "",
};

const textData = {
  main_data: {
    license_number_secretariat: "",
    license_number: "",
    request_number: "",
    license_start_date: "",
    license_end_date: "",
    license_type: "",
    building_type: "",
    buildings_number: "",
    license_separated_another_license: "",
    main_use: "",
    sub_use: "",
    total_land_area: "",
    building_description: "",
  },
  applicant_data: {
    applicant_characteristics: "",
    applicant_id: "",
    applicant_name: "",
    phone: "",
    email: "",
  },
  ownershipData: {
    ownership_type: "",
    ownership_number: "",
    ownership_date: "",
    scheme_number: "",
    plot_number: "",
  },
  surveyDecisionData: {
    survey_decision_number: "",
    survey_decision_date: "",
  },
  geolocationData: {
    honesty: "",
    municipal: "",
    district: "",
    planned_number: "",
    block_number: "",
  },
  midpointCoordinates: {
    abscissa: "",
    y_coordinate: "",
  },
  contractingData: {
    supervising_engineering_office: "",
    designer_engineering_office: "",
  },
  ownerData: [
    {
      inde: 1,
      owner_name: "",
      id_number: "",
    },
  ],
  landData: [
    {
      index: 1,
      piece_number: "",
      land_area: "",
      land_area_plan: "",
    },
  ],
  buildingComponents: [
    {
      building_component: "",
      component_usage: "",
      construction_ratio: "",
      floor_area: "",
      floors_number: "",
      units_number: "",
    },
  ],
  coordinates: [
    {
      coordinate_number: "",
      abscissa: "",
      y_coordinate: "",
    },
  ],
  pledges: [
    {
      pledge: "",
    },
  ],
  dimensions_boundaries: {
    instrument_limit: {
      north_instrument_limit: "",
      east_instrument_limit: "",
      south_instrument_limit: "",
      west_instrument_limit: "",
    },
    nature_limit: {
      north_nature_limit: "",
      east_nature_limit: "",
      south_nature_limit: "",
      west_nature_limit: "",
    },
    instrument_length: {
      north_instrument_length: "",
      east_instrument_length: "",
      south_instrument_length: "",
      west_instrument_length: "",
    },
    nature_length: {
      north_nature_length: "",
      east_nature_length: "",
      south_nature_length: "",
      west_nature_length: "",
    },
    bouncing: {
      north_bouncing: "",
      east_bouncing: "",
      south_bouncing: "",
      west_bouncing: "",
    },
    prominence: {
      north_prominence: "",
      east_prominence: "",
      south_prominence: "",
      west_prominence: "",
    },
  },
};
